import "./globals.css";
import { Inter } from "next/font/google";
import { ServerList } from "@/components/ServerList/ServerList";
import { NextAuthProvider } from "@/lib/auth/Provider";
import { TrpcProvider } from "@/lib/trpc/Provider";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <TrpcProvider>
        <NextAuthProvider>
          <ServerList />
          {children}
        </NextAuthProvider>
      </TrpcProvider>
    </body>
  </html>
);

export default RootLayout;
