import "./globals.css";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";
import { NextAuthProvider } from "@/lib/auth/Provider";
import { TrpcProvider } from "@/lib/trpc/Provider";
import { serverTrpc } from "@/lib/trpc/api";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  const servers = await serverTrpc.servers.getServers.query();
  if (!servers) throw new Error("No servers");
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </TrpcProvider>
      </body>
    </html>
  );
};

export default RootLayout;
